# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "debug"

image:
  repository: "milou666/ibm-ui"
  tag: "latest"
  pullPolicy: IfNotPresent
  port: 3000

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: false
